
CREATE DATABASE PrepWiseDB;
USE PrepWiseDB;

CREATE TABLE User (
    STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_NAME VARCHAR(100) NOT NULL,
    STUDENT_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    STUDENT_PASSWORD VARCHAR(255) NOT NULL,
    PREFERRED_MODE VARCHAR(10),
    CREATED_AT DATE NOT NULL
);


CREATE TABLE Exam (
    SUBJECT_NAME VARCHAR(100) PRIMARY KEY,
    EXAM_DATE DATE NOT NULL,
    CHAPTERS TEXT,
    DIFFICULTY_LEVEL VARCHAR(20) NOT NULL,
    STUDENT_ID INT NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES User(STUDENT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE Daily_Plan (
    PLAN_DATE DATE PRIMARY KEY,
    TASKS TEXT,
    PROGRESS_RATIO INT DEFAULT 0 CHECK (PROGRESS_RATIO BETWEEN 0 AND 100),
    STUDENT_ID INT NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES User(STUDENT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE Pomodoro_Session (
    SESSION_ID INT AUTO_INCREMENT PRIMARY KEY,
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    STUDENT_ID INT NOT NULL,
    PLAN_DATE DATE NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES User(STUDENT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (PLAN_DATE) REFERENCES Daily_Plan(PLAN_DATE)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE Admin (
    ADMIN_ID INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    ADMIN_NAME VARCHAR(100) NOT NULL,
    ADMIN_EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(15)
);


CREATE TABLE Reported_Problem (
    PROBLEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    ISSUE_DESCRIPTION TEXT NOT NULL,
    PROBLEM_DATE DATE NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES User(STUDENT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);



-- Admin (system has one admin)
INSERT INTO Admin (ADMIN_NAME, ADMIN_EMAIL, PHONE_NUMBER)
VALUES
('System Admin', 'admin@prepwise.app', '0501234567');


INSERT INTO User (STUDENT_NAME, STUDENT_EMAIL, STUDENT_PASSWORD, PREFERRED_MODE, CREATED_AT)
VALUES
('User One', 'user1@prepwise.app', 'pw1', '25_5', '2025-10-20'),
('User Two', 'user2@prepwise.app', 'pw2', '50_10', '2025-10-21');


INSERT INTO Exam (SUBJECT_NAME, EXAM_DATE, CHAPTERS, DIFFICULTY_LEVEL, STUDENT_ID)
VALUES
('Database Systems', '2025-12-10', 'ER Diagram; SQL Queries', 'Hard', 1),
('Web Development', '2025-12-05', 'HTML; CSS; JS', 'Medium', 2);


INSERT INTO Daily_Plan (PLAN_DATE, TASKS, PROGRESS_RATIO, STUDENT_ID)
VALUES
('2025-11-01', 'Review SQL basics', 40, 1),
('2025-11-02', 'Finish CSS exercises', 70, 2);


INSERT INTO Pomodoro_Session (START_TIME, END_TIME, STUDENT_ID, PLAN_DATE)
VALUES
('09:00:00','09:25:00', 1, '2025-11-01'),
('10:00:00','10:25:00', 2, '2025-11-02');


INSERT INTO Reported_Problem (USER_ID, ISSUE_DESCRIPTION, PROBLEM_DATE)
VALUES
(1, 'Unable to save daily plan progress', '2025-11-01'),
(2, 'Timer not resetting after session end', '2025-11-02');